BlogWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('users/', views.get_users_page, name='users'),
    path('blogs/', views.get_blogs_page, name='blogs'),
    path('blogs/<int:blog_id>/', views.get_blog_detail_page, name='blog_detail'),
    path('blogs/<int:blog_id>/comments/', views.get_blog_comments_page, name='blog_comments'),
    path('categories/', views.get_categories_page, name='categories'),
]

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.username

blog/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    data_published = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    data_posted = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username + ' commented on ' + self.post.title


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

account/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.template import loader

from .models import Post, Comment, Category


def index(request):
    template = loader.get_template('index.html')
    return HttpResponse(template.render({}, request))


def get_users_page(request):
    template = loader.get_template('users.html')
    users = get_user_model().objects.all()
    context = {
        'users': users,
    }
    return HttpResponse(template.render(context, request))


def get_blogs_page(request):
    template = loader.get_template('blogs.html')
    blogs = Post.objects.all()
    context = {
        'blogs': blogs,
    }
    return HttpResponse(template.render(context, request))


def get_blog_detail_page(request, blog_id):
    template = loader.get_template('blog_detail.html')
    post = Post.objects.get(id=blog_id)
    context = {
        'post': post,
    }
    return HttpResponse(template.render(context, request))


def get_blog_comments_page(request, blog_id):
    template = loader.get_template('blog_comments.html')
    comments = Comment.objects.filter(post=blog_id)
    context = {
        'post_title': Post.objects.get(id=blog_id).title,
        'comments': comments,
    }
    return HttpResponse(template.render(context, request))


def get_categories_page(request):
    template = loader.get_template('categories.html')
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return HttpResponse(template.render(context, request))

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
		{% block title %}
		{% endblock %}
	</title>
</head>
<body>
<main>
	{% block content %}
	{% endblock %}

</main>
</body>
</html>

blog/templates/blog_comments.html
{% extends 'base.html' %}

{% block content %}
	<h1>Comments of {{ post_title }}</h1>
	{% for comment in comments %}
		<h2>{{ forloop.counter }}- {{ comment.content }}</h2>
		<li>Author: {{ comment.user }}</li>
		<li>posted in: {{ comment.data_posted }}</li>
	{% endfor %}


{% endblock %}
```

blog/templates/blog_detail.html
{% extends 'base.html' %}

{% block content %}
	<h1>{{ post.title }}</h1>
	<h4>Published Date: {{ post.data_published }}
	Category: post.category
	</h4>
	<p>{{ post.content }}</p>

	<hr/>
	<p><a href="{% url 'blog:blog_comments' post.id %}">comments</a></p>
{% endblock %}
```

blog/templates/blogs.html
{% extends 'base.html' %}

{% block content %}
	<h1>Blogs</h1>
	{% for blog in blogs %}
		<a href="{% url 'blog:blog_detail' blog.id %}">
			<h2>{{ blog.title }}</h2>
		</a>
	{% endfor %}
{% endblock %}
```

blog/templates/categories.html
{% extends 'base.html' %}

{% block content %}
	<h1>All Categories in the Website</h1>
	<ul>
	{% for category in categories %}
		<li>{{ category.name }}</li>
	{% endfor %}
{% endblock %}

blog/templates/index.html
{% extends "base.html" %}

{% block title %}
	Home
{% endblock %}

{% block content %}
	<ul>
		<li><a href="{% url 'blog:index' %}">Home</a></li>
		<li><a href="{% url 'blog:users' %}">Users</a></li>
		<li><a href="{% url 'blog:blogs' %}">Blogs</a></li>
		<li><a href="{% url 'blog:categories' %}">Categories</a></li>
	</ul>
{% endblock %}

blog/templates/users.html
{% extends 'base.html' %}

{% block title %}Users{% endblock %}
{% block content %}
	<h1>Users</h1>
	<ul>
		{% for user in users %}
			<li>{{ user.username }}, {{ user.email }}</li>
			<br/>
		{% endfor %}
	</ul>
{% endblock %}